apiVersion: v1
kind: ConfigMap
metadata:
  name: fiapstore-config
  namespace: fiap-store
  labels:
    app: fiapstore-api
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:8080"
  Logging__LogLevel__Default: "Information"
  Logging__LogLevel__Microsoft.AspNetCore: "Warning"
