apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiapstore-api
  namespace: fiap-store
  labels:
    app: fiapstore-api
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fiapstore-api
  template:
    metadata:
      labels:
        app: fiapstore-api
        version: v1
    spec:
      containers:
      - name: fiapstore-api
        image: <SEU_ECR_URI>:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        envFrom:
        - configMapRef:
            name: fiapstore-config
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 0
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 30
      restartPolicy: Always
