apiVersion: v1
kind: Service
metadata:
  name: fiapstore-api-service
  namespace: fiap-store
  labels:
    app: fiapstore-api
spec:
  type: LoadBalancer
  selector:
    app: fiapstore-api
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  sessionAffinity: None
